version: 0.5.{build}

artifacts:
  - path: ./build/vim_ahk.exe
    name: Main Executable

#init:
#  # Initialise remote desktop stuff
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  # Chocolaty install autohotkey
  - cinst autohotkey.install
  - cmd: refreshenv

build_script:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cmd: mkdir "C:\Users\appveyor\AppData\Local\Temp\~Ahk2Exe~build"
  - cmd: ./build/build.bat

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: ''
  provider: GitHub
  auth_token: $(github_access) # your encrypted token from GitHub
  artifact: /.*Executable/
  draft: false
  prerelease: false
  skip_tags: true
  on:
    APPVEYOR_REPO_TAG: true

test: off
